# ## FIRST LINE/ROW: Info & Status
format = """
$username\
$directory\
$git_branch\
$fill\
$dart\
$time
$character\
"""

# First param ─┌
[username]
format = " [╭─]($style)"
style_user = "bold gray"
style_root = "bold red"
show_always = true


[directory]
truncation_length = 2
truncation_symbol = '  ❯ '
style = "bg:black fg:cyan"

[time]
disabled = false
format = "[  $time]($style) ─╮"
style = "bold cyan"

# Prompt: param 2 └─
[character]
success_symbol = " [╰─](bold green)"
error_symbol = " [╰─](bold red)"


[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "
format = "via [$symbol($version)]($style)"


[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "bold bright-green"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[haskell]
symbol = "λ "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
# #pyenv_version_name = true
# format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
# style = "bold yellow"
# pyenv_prefix = "venv "
# python_binary = ["./venv/bin/python", "python", "python3", "python2"]
# detect_extensions = ["py"]
# version_format = "v${raw}"

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

# [nodejs]
# format = "via [ Node.js $version](bold green) "
# detect_files = ["package.json", ".node-version"]
# detect_folders = ["node_modules"]
