[[manager.prepend_keymap]]
on = ["l"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = ["c", "a"]
run = "plugin archive"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on = "y"
run = ['''
	shell 'echo "$@" | xclip -i -selection clipboard -t text/uri-list' --confirm
''', "yank"]
desc = "Yank to clipboard"

[[manager.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''
desc = "Open in QuickLook"
